### ISSUE TITLE
Add option to make gradlew executable

### ISSUE THREAD

**Issue by twbutler** [jmnarloch/gocd-gradle-plugin#3] opened 2016-01-05 20:30 UTC
Jakub,

Hello - this is really a feature request I suppose. We are working with gradle wrapper quite a bit, and a common issue we see is that after checking out (or cloning) a project from source control, the gradlew file is not executable. This is not a problem on Windows, but it definitely is on Linux/Unix. I see that Jenkins has support for making the gradlew file executable before invoking it (see attached), and really wish that the GoCD plugin also had this option.  

I tried to work around this by defining another task that performs a "chmod +x gradlew" just before the gradle task.  This works fine on a Linux agent, but causes a failure on Windows agents since chmod is not a Windows command.  It seems that having the plugin perform the chmod would be a cleaner way to go...  please let me know what you think...

Regards,
Trevor

![make-gradlew-exec](https://cloud.githubusercontent.com/assets/15386618/12126749/ff0f833a-b3c0-11e5-95b8-ce7479e2502d.JPG)

**Comment by jmnarloch** [comment] 2016-01-05 20:48
OK, that's actually a good idea, but before I will do this and release a version I think that you should be able to do a workaround for that in git directly. Git allows to store the basic file permissions http://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows

So you should be able to make the file executable and commit that into your repository.

**Comment by twbutler** [comment] 2016-01-05 20:56
Jakub,

Thank you for considering this. I agree with your suggestion that ideally the file should be checked in with the executable property set.

In my case, I do not have control over the Git repos – we are a large company and there are hundreds of developers working on various projects, all with different teams and standards.  I am using GoCD to automate continuous delivery for some of these projects, and hence I am looking for support in Go to handle the cases where the gradlew file is not executable.

Thanks,
Trevor

**Comment by jmnarloch** [comment] 2016-01-06 18:59
Hey I've addressed this issue and made the release: https://github.com/jmnarloch/gocd-gradle-plugin/releases/tag/1.0.2

I try to figure out what is going on with the second, problem and I had problem to reproduce that, though I've added extra check in code so that the problem should not occur once again.

Can you check if this what you wanted?

**Comment by twbutler** [comment] 2016-01-06 19:05
Thanks Jakub…

As before you really turned around these requests so quickly, which is very nice.  Absolutely, I will install the latest version and try it today, then let you know how it goes.

Thanks,
Trevor

**Comment by twbutler** [comment] 2016-01-06 20:13
Jakub,

I have the 1.0.2 version installed now, and am trying it. _However, unfortunately, I do not see any improvement._ 

Currently I have disabled my Windows agents and so the only place for work to occur is on the Linux agent.  I have modified my Gradle tasks for the pipeline that was failing so that all of them use the new "Add executable permission to wrapper script". Rerunning the pipeline manually a few times, I still see what looks like an incorrect path to "gradlew" being specified - '\' char after "/var/lib/go-agent/pipelines" :

19:50:32.293 [go] Start to execute task: Plugin with ID: gradle.task.plugin.
19:50:32.430 Cannot run program "**/var/lib/go-agent/pipelines\audit-service/gradlew**" (in directory "pipelines\audit-service"): error=2, No such file or directory
19:50:32.433 java.io.IOException: Cannot run program "/var/lib/go-agent/pipelines\audit-service/gradlew" (in directory "pipelines\audit-service"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:113)
    at io.jmnarloch.cd.go.plugin.gradle.GradleTaskExecutor.execute(GradleTaskExecutor.java:62)
    at io.jmnarloch.cd.go.plugin.api.command.TaskCommand.execute(TaskCommand.java:64)
    at io.jmnarloch.cd.go.plugin.api.dispatcher.ApiRequestDispatcherBuilder$ApiRequestDispatcherImpl.dispatch(ApiRequestDispatcherBuilder.java:176)
    at io.jmnarloch.cd.go.plugin.api.task.AbstractDispatchingTask.handle(AbstractDispatchingTask.java:107)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)

In addition, after the task fails and stops running, if I go into the workspace directory on the Agent filesystem, I do not see that gradlew is being made executable: 

go@gocd-lax:/var/lib/go-agent/pipelines/audit-service$ ls -al
total 96
drwxrwxr-x 12 go go 4096 Jan  6 19:50 .
drwxrwxr-x  5 go go 4096 Dec 24 15:54 ..
:
**-rw-rw-r--**  1 go go 5080 Jan  6 19:35 gradlew
-rw-rw-r--  1 go go 2404 Dec 23 21:24 gradlew.bat
:

**Comment by jmnarloch** [comment] 2016-01-07 23:51
Regarding the executable permission, I've added the setting to GUI, you have to edit the Gradle job and enable it, there is no migration available for the jobs configuration, so the property appears as undefined - disabled.

As for the backslash, I made stupid mistake a next release had to be made, though I still don't think that the problem itself is caused by the plugin, this is most likely that the slash is being send from Go Server to the agent.

Please check: https://github.com/jmnarloch/gocd-gradle-plugin/releases/tag/1.0.3

**Comment by twbutler** [comment] 2016-01-08 20:18
Thanks,

I will try the new version as soon as I can…

Trevor

**Comment by twbutler** [comment] 2016-01-08 21:29
I tried 1.0.3 and can now confirm that executable permission is being performed on the gradlew file:

-rw**x**rw-r--  1 go go 5080 Jan  6 19:35 gradlew
-rw-rw-r--  1 go go 2404 Dec 23 21:24 gradlew.bat

Can we keep this issue open for a bit longer while I do some more testing?  
Thanks...

**Comment by jmnarloch** [comment] 2016-01-10 16:40
Closing this issue.

**Closed as completed by jmnarloch** 2016-01-10 16:40 UTC
